--TABLES
SET default_tablespace = ts_licpub_data;
SET default_with_oids = false;

--Se crea tabla partida_generica
CREATE TABLE if not exists licpub.partida_generica
(
    id_partida_generica integer NOT NULL,
    id_concepto integer NOT NULL,
    descripcion character varying(500) NOT NULL
)TABLESPACE ts_licpub_data;

ALTER TABLE licpub.partida_generica OWNER TO licpub;

SET default_tablespace = ts_licpub_idx;

ALTER TABLE licpub.partida_generica ADD CONSTRAINT partida_generica_pkey PRIMARY KEY (id_partida_generica)
	USING INDEX TABLESPACE ts_licpub_idx;

ALTER TABLE ONLY licpub.partida_generica
    ADD CONSTRAINT partida_generica_fk FOREIGN KEY (id_concepto)
    REFERENCES licpub.concepto(id_concepto) DEFERRABLE INITIALLY DEFERRED;

--Inserts
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2110, 2100, 'Materiales, útiles y equipos menores de oficina');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2120, 2100, 'Materiales y útiles de impresión y reproducción');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2130, 2100, 'Material estadístico y geográfico');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2140, 2100, 'Materiales, útiles y equipos menores de tecnologías de la información y comunicaciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2150, 2100, 'Material impreso e información digital');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2160, 2100, 'Material de limpieza');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2170, 2100, 'Materiales y útiles de enseñanza');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2180, 2100, 'Materiales para el registro e identificación de bienes y personas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2210, 2200, 'Productos alimenticios para personas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2220, 2200, 'Productos alimenticios para animales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2230, 2200, 'Utensilios para el servicio de alimentación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2310, 2300, 'Productos alimenticios, agropecuarios y forestales adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2320, 2300, 'Insumos textiles adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2330, 2300, 'Productos de papel, cartón e impresos adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2340, 2300, 'Combustibles, lubricantes, aditivos, carbón y sus derivados adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2350, 2300, 'Productos químicos, farmacéuticos y de laboratorio adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2360, 2300, 'Productos metálicos y a base de minerales no metálicos adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2370, 2300, 'Productos de cuero, piel, plástico y hule adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2380, 2300, 'Mercancías adquiridas para su comercialización');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2390, 2300, 'Otros productos adquiridos como materia prima');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2410, 2400, 'Productos minerales no metálicos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2420, 2400, 'Cemento y productos de concreto');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2430, 2400, 'Cal, yeso y productos de yeso');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2440, 2400, 'Madera y productos de madera');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2450, 2400, 'Vidrio y productos de vidrio');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2460, 2400, 'Material eléctrico y electrónico');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2470, 2400, 'Artículos metálicos para la construcción');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2480, 2400, 'Materiales complementarios');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2490, 2400, 'Otros materiales y artículos de construcción y reparación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2510, 2500, 'Productos químicos básicos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2520, 2500, 'Fertilizantes, pesticidas y otros agroquímicos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2530, 2500, 'Medicinas y productos farmacéuticos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2540, 2500, 'Materiales, accesorios y suministros médicos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2550, 2500, 'Materiales, accesorios y suministros de laboratorio');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2560, 2500, 'Fibras sintéticas, hules, plásticos y derivados');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2590, 2500, 'Otros productos químicos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2610, 2600, 'Combustibles, lubricantes y aditivos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2710, 2700, 'Vestuario y uniformes');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2720, 2700, 'Prendas de seguridad y protección personal');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2730, 2700, 'Artículos deportivos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2740, 2700, 'Productos textiles');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2750, 2700, 'Blancos y otros productos textiles, excepto prendas de vestir');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2810, 2800, 'Sustancias y materiales explosivos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2820, 2800, 'Materiales de seguridad Pública');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2830, 2800, 'Prendas de protección para seguridad Pública y nacional');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2910, 2900, 'Herramientas menores');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2920, 2900, 'Refacciones y accesorios menores de edificios');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2930, 2900, 'Refacciones y accesorios menores de mobiliario y equipo de administración, educacional y recreativo');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2940, 2900, 'Refacciones y accesorios menores de equipo de cómputo y tecnologías de la información');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2950, 2900, 'Refacciones y accesorios menores de equipo e instrumental médico y de laboratorio');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2960, 2900, 'Refacciones y accesorios menores de equipo de transporte');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2970, 2900, 'Refacciones y accesorios menores de equipo de defensa y seguridad');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2980, 2900, 'Refacciones y accesorios menores de maquinaria y otros equipos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (2990, 2900, 'Refacciones y accesorios menores otros bienes muebles');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3110, 3100, 'Energía eléctrica');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3120, 3100, 'Gas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3130, 3100, 'Agua');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3140, 3100, 'Telefonía tradicional');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3150, 3100, 'Telefonía celular');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3160, 3100, 'Servicios de telecomunicaciones y satélites');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3170, 3100, 'Servicios de acceso de Internet, redes y procesamiento de información');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3180, 3100, 'Servicios postales y telegráficos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3190, 3100, 'Servicios integrales y otros servicios');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3210, 3200, 'Arrendamiento de terrenos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3220, 3200, 'Arrendamiento de edificios');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3230, 3200, 'Arrendamiento de mobiliario y equipo de administracion, educacional y recreativo');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3240, 3200, 'Arrendamiento de equipo e instrumental médico y de laboratorio');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3250, 3200, 'Arrendamiento de equipo de transporte');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3260, 3200, 'Arrendamiento de maquinaria, otros equipos y herramientas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3270, 3200, 'Arrendamiento de activos intangibles');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3280, 3200, 'Arrendamiento financiero');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3290, 3200, 'Otros arrendamientos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3310, 3300, 'Servicios legales, de contabilidad, auditoria y relacionados');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3320, 3300, 'Servicios de diseño, arquitectura, ingeniería y actividades relacionadas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3330, 3300, 'Servicios de consultoría administrativa, procesos, técnica y en tecnologías de la información');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3340, 3300, 'Servicios de capacitación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3350, 3300, 'Servicios de investigación científica y desarrollo');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3360, 3300, 'Servicios de apoyo administrativo, traducción, fotocopiado e impresión');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3370, 3300, 'Servicios de protección y seguridad');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3380, 3300, 'Servicios de vigilancia');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3390, 3300, 'Servicios profesionales, científicos y técnicos integrales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3410, 3400, 'Servicios financieros y bancarios');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3420, 3400, 'Servicios de cobranza, investigación crediticia y similar');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3430, 3400, 'Servicios de recaudación, traslado y custodia de valores');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3440, 3400, 'Seguros de responsabilidad patrimonial y fianzas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3450, 3400, 'Seguro de bienes patrimoniales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3460, 3400, 'Almacenaje, envase y embalaje');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3470, 3400, 'Fletes y maniobras');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3480, 3400, 'Comisiones por ventas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3490, 3400, 'Servicios financieros, bancarios y comerciales integrales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3510, 3500, 'Conservación y mantenimiento menor de inmuebles');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3520, 3500, 'Instalación, reparación y mantenimiento de mobiliario y equipo de administracion, educacional y recreativo');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3530, 3500, 'Instalación, reparación y mantenimiento de equipo de cómputo y tecnología de la información');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3540, 3500, 'Instalación, reparación y mantenimiento de equipo e instrumental médico y de laboratorio');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3550, 3500, 'Reparación y mantenimiento de equipo de transporte');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3560, 3500, 'Reparación y mantenimiento de equipo de defensa y seguridad');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3570, 3500, 'Instalación, reparación y mantenimiento de maquinaria, otros equipos y herramienta');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3580, 3500, 'Servicios de limpieza y manejo de desechos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3590, 3500, 'Servicios de jardinería y fumigación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3610, 3600, 'Difusión por radio, televisión y otros medios de mensajes sobre programas y actividades gubernamentales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3620, 3600, 'Difusión por radio, televisión y otros medios de mensajes comerciales para promover la venta de bienes o servicios');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3630, 3600, 'Servicios de creatividad, preproducción y producción de publicidad, excepto Internet');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3640, 3600, 'Servicios de revelado de fotografías');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3650, 3600, 'Servicios de la industria fílmica, del sonido y del video');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3660, 3600, 'Servicio de creación y difusión de contenido exclusivamente a través de Internet');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3690, 3600, 'Otros servicios de información');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3710, 3700, 'Pasajes aéreos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3720, 3700, 'Pasajes terrestres');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3730, 3700, 'Pasajes marítimos, lacustres y fluviales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3740, 3700, 'Autotransporte');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3750, 3700, 'Viáticos en el país');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3760, 3700, 'Viáticos en el extranjero');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3770, 3700, 'Gastos de instalación y traslado de menaje');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3780, 3700, 'Servicios integrales de traslado y viáticos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3790, 3700, 'Otros servicios de traslado y hospedaje');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3810, 3800, 'Gastos de ceremonial');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3820, 3800, 'Gastos de orden social y cultural');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3830, 3800, 'Congresos y convenciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3840, 3800, 'Exposiciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3850, 3800, 'Gastos de representación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3910, 3900, 'Servicios funerarios y de cementerios');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3920, 3900, 'Impuestos y derechos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3930, 3900, 'Impuestos y derechos de importación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3940, 3900, 'Sentencias y resoluciones judiciales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3950, 3900, 'Penas, multas, accesorios y actualizaciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3960, 3900, 'Otros gastos por responsabilidades');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3970, 3900, 'Utilidades');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3980, 3900, 'Impuesto sobre nóminas y otros que se deriven de una relación laboral');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (3990, 3900, 'Otros servicios generales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5110, 5100, 'Muebles de oficina y estantería');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5120, 5100, 'Muebles, excepto de oficina y estantería');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5130, 5100, 'Bienes artísticos, culturales y científicos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5140, 5100, 'Objetos de valor');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5150, 5100, 'Equipo de cómputo y de tecnologías de la información');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5190, 5100, 'Otros mobiliarios y equipos de administracion');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5210, 5200, 'Equipos y aparatos audiovisuales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5220, 5200, 'Aparatos deportivos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5230, 5200, 'Cámaras fotográficas y de video');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5290, 5200, 'Otro mobiliario y equipo educacional y recreativo');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5310, 5300, 'Equipo medico y de laboratorio');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5320, 5300, 'Instrumental medico y de laboratorio');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5410, 5400, 'Vehículos y equipo terrestre');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5420, 5400, 'Carrocerías y remolques');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5430, 5400, 'Equipo aeroespacial');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5440, 5400, 'Equipo ferroviario');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5450, 5400, 'Embarcaciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5490, 5400, 'Otros equipos de transporte');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5510, 5500, 'Equipo de defensa y seguridad');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5610, 5600, 'Maquinaria y equipo agropecuario');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5620, 5600, 'Maquinaria y equipo industrial');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5630, 5600, 'Maquinaria y equipo de construcción');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5640, 5600, 'Sistemas de aire acondicionado, calefacción y de refrigeración industrial y comercial');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5650, 5600, 'Equipo de comunicación y telecomunicación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5660, 5600, 'Equipos de generación eléctrica, aparatos y accesorios eléctricos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5670, 5600, 'Herramientas y máquinas-herramienta');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5690, 5600, 'Otros equipos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5710, 5700, 'Bovinos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5720, 5700, 'Porcinos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5730, 5700, 'Aves');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5740, 5700, 'Ovinos y caprinos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5750, 5700, 'Peces y acuicultura');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5760, 5700, 'Equinos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5770, 5700, 'Especies menores y de zoológico');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5780, 5700, 'Árboles y plantas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5790, 5700, 'Otros activos biológicos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5810, 5800, 'Terrenos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5820, 5800, 'Viviendas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5830, 5800, 'Edificios no residenciales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5890, 5800, 'Otros bienes inmuebles');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5910, 5900, 'Software');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5920, 5900, 'Patentes');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5930, 5900, 'Marcas');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5940, 5900, 'Derechos');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5950, 5900, 'Concesiones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5960, 5900, 'Franquicias');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5970, 5900, 'Licencias informáticas e intelectuales');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5980, 5900, 'Licencias industriales, comerciales y otras');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (5990, 5900, 'Otros activos intangibles');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6120, 6100, 'Edificación no habitacional');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6130, 6100, 'Construcción de obras para el abastecimiento de agua, petróleo, gas, electricidad y telecomunicaciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6150, 6100, 'Construcción de vías de comunicación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6160, 6100, 'Otras Construcciones de ingeniería civil u obra pesada');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6170, 6100, 'Instalaciones y equipamiento en Construcciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6190, 6100, 'Trabajos de acabados en edificaciones y otros trabajos especializados');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6210, 6200, 'Edificación habitacional');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6220, 6200, 'Edificación no habitacional');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6230, 6200, 'Construcción de obras para el abastecimiento de agua, petróleo, gas, electricidad y telecomunicaciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6240, 6200, 'División de terrenos y construcción de obras de urbanización');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6250, 6200, 'Construcción de vías de comunicación');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6260, 6200, 'Otras construcciones de ingeniería civil u obra pesada');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6270, 6200, 'Instalaciones y equipamiento en construcciones');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6290, 6200, 'Trabajos de acabados en edificaciones y otros trabajos especializados');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6310, 6300, 'Estudios, formulación y evaluación de proyectos productivos no incluidos en conceptos anteriores de este capitulo');
insert into partida_generica (id_partida_generica, id_concepto, descripcion) values (6320, 6300, 'Ejecución de proyectos productivos no incluidos en conceptos anteriores de este capitulo');
