--TABLES
SET default_tablespace = ts_licpub_data;
SET default_with_oids = false;

--Se crea tabla partida_especifica
CREATE TABLE if not exists licpub.partida_especifica
(
    id_partida_especifica integer NOT NULL,
    id_partida_generica integer NOT NULL,
    descripcion character varying(500) NOT NULL
)TABLESPACE ts_licpub_data;

ALTER TABLE licpub.partida_especifica OWNER TO licpub;

SET default_tablespace = ts_licpub_idx;

ALTER TABLE licpub.partida_especifica ADD CONSTRAINT partida_especifica_pkey PRIMARY KEY (id_partida_especifica)
	USING INDEX TABLESPACE ts_licpub_idx;

ALTER TABLE ONLY licpub.partida_especifica
    ADD CONSTRAINT partida_especifica_fk FOREIGN KEY (id_partida_generica)
    REFERENCES licpub.partida_generica(id_partida_generica) DEFERRABLE INITIALLY DEFERRED;

--Inserts
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21101, 2110, 'Materiales y útiles de oficina');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21201, 2120, 'Materiales y útiles de impresión y reproducción');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21301, 2130, 'Material estadístico y geográfico');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21401, 2140, 'Materiales y útiles consumibles para el procesamiento en equipos y bienes informáticos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21501, 2150, 'Material de apoyo informativo');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21502, 2150, 'Material para información en actividades de investigación científica y tecnológica');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21601, 2160, 'Material de limpieza');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21701, 2170, 'Materiales y suministros para planteles educativos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (21801, 2180, 'Materiales para el registro e identificación de bienes y personas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22101, 2210, 'Productos alimenticios para el Ejercito, Fuerza Aérea y Armada Mexicanos, y para los efectivos que participen en programas de seguridad Pública');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22102, 2210, 'Productos alimenticios para personas derivado de la prestación de servicios públicos en unidades de salud, educativas, de readaptación social y otras');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22103, 2210, 'Productos alimenticios para el personal que realiza labores en campo o de supervisión');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22104, 2210, 'Productos alimenticios para el personal en las instalaciones de las dependencias y entidades');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22105, 2210, 'Productos alimenticios para la población en caso de desastres naturales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22106, 2210, 'Productos alimenticios para el personal derivado de actividades extraordinarias');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22201, 2220, 'Productos alimenticios para animales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (22301, 2230, 'Utensilios para el servicio de alimentación');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23101, 2310, 'Productos alimenticios, agropecuarios y forestales adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23201, 2320, 'Insumos textiles adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23301, 2330, 'Productos de papel, cartón e impresos adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23401, 2340, 'Combustibles, lubricantes, aditivos, carbón y sus derivados adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23501, 2350, 'Productos químicos, farmacéuticos y de laboratorio adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23601, 2360, 'Productos metálicos y a base de minerales no metálicos adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23701, 2370, 'Productos de cuero, piel, plástico y hule adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23801, 2380, 'Mercancías para su comercialización en tiendas del sector publico');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23901, 2390, 'Otros productos adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (23902, 2390, 'Petróleo, gas y sus derivados adquiridos como materia prima');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24101, 2410, 'Productos minerales no metálicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24201, 2420, 'Cemento y productos de concreto');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24301, 2430, 'Cal, yeso y productos de yeso');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24401, 2440, 'Madera y productos de madera');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24501, 2450, 'Vidrio y productos de vidrio');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24601, 2460, 'Material eléctrico y electrónico');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24701, 2470, 'Artículos metálicos para la construcción');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24801, 2480, 'Materiales complementarios');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (24901, 2490, 'Otros materiales y artículos de construcción y reparación');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (25101, 2510, 'Productos químicos básicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (25201, 2520, 'Plaguicidas, abonos y fertilizantes');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (25301, 2530, 'Medicinas y productos farmacéuticos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (25401, 2540, 'Materiales, accesorios y suministros médicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (25501, 2550, 'Materiales, accesorios y suministros de laboratorio');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (25601, 2560, 'Fibras sintéticas, hules, plásticos y derivados');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (25901, 2590, 'Otros productos químicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (26102, 2610, 'Combustibles, lubricantes y aditivos para vehículos terrestres, aéreos, marítimos, lacustres y fluviales destinados a servicios públicos y la operación de programas públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (26103, 2610, 'Combustibles, lubricantes y aditivos para vehículos terrestres, aéreos, marítimos, lacustres y fluviales destinados a servicios administrativos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (26104, 2610, 'Combustibles, lubricantes y aditivos para vehículos terrestres, aéreos, marítimos, lacustres y fluviales asignados a servidores públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (26105, 2610, 'Combustibles, lubricantes y aditivos para maquinaria, equipo de producción y servicios administrativos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (27101, 2710, 'Vestuario y uniformes');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (27201, 2720, 'Prendas de protección personal');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (27301, 2730, 'Artículos deportivos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (27401, 2740, 'Productos textiles');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (27501, 2750, 'Blancos y otros productos textiles, excepto prendas de vestir');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (28101, 2810, 'Sustancias y materiales explosivos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (28201, 2820, 'Materiales de seguridad Pública');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (28301, 2830, 'Prendas de protección para seguridad Pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29101, 2910, 'Herramientas menores');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29201, 2920, 'Refacciones y accesorios menores de edificios');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29301, 2930, 'Refacciones y accesorios menores de mobiliario y equipo de administración, educacional y recreativo');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29401, 2940, 'Refacciones y accesorios para equipo de cómputo y telecomunicaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29501, 2950, 'Refacciones y accesorios menores de equipo e instrumental médico y de laboratorio');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29601, 2960, 'Refacciones y accesorios menores de equipo de transporte');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29701, 2970, 'Refacciones y accesorios menores de equipo de defensa y seguridad');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29801, 2980, 'Refacciones y accesorios menores de maquinaria y otros equipos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (29901, 2990, 'Refacciones y accesorios menores otros bienes muebles');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31101, 3110, 'Servicio de energía eléctrica');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31201, 3120, 'Servicio gas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31301, 3130, 'Servicio de agua');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31401, 3140, 'Servicio telefónico convencional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31501, 3150, 'Servicio de telefonía celular');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31601, 3160, 'Servicios de radiolocalización');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31602, 3160, 'Servicios de telecomunicaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31603, 3160, 'Servicios de Internet');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31701, 3170, 'Servicios de conducción de señales analógicas y digitales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31801, 3180, 'Servicio postal');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31802, 3180, 'Servicio telegráfico');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31901, 3190, 'Servicios integrales de telecomunicación');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31902, 3190, 'Contratación de otros servicios');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31903, 3190, 'Servicios generales para planteles educativos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (31904, 3190, 'Servicios integrales de infraestructura de computo');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32301, 3230, 'Arrendamiento de equipo y bienes informáticos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32302, 3230, 'Arrendamiento de mobiliario');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32303, 3230, 'Arrendamiento de equipo de telecomunicaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32401, 3240, 'Arrendamiento de equipo e instrumental médico y de laboratorio');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32501, 3250, 'Arrendamiento de vehículos terrestres, aéreos, marítimos, lacustres y fluviales para la ejecución de programas de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32502, 3250, 'Arrendamiento de vehículos terrestres, aéreos, marítimos, lacustres y fluviales para servicios públicos y la operación de programas públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32503, 3250, 'Arrendamiento de vehículos terrestres, aéreos, marítimos, lacustres y fluviales para servicios administrativos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32504, 3250, 'Arrendamiento de vehículos terrestres, aéreos, marítimos, lacustres y fluviales para desastres naturales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32505, 3250, 'Arrendamiento de vehículos terrestres, aéreos, marítimos, lacustres y fluviales para servidores públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32601, 3260, 'Arrendamiento de maquinaria y equipo');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32701, 3270, 'Patentes, derechos de autor, regalías y otros');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32901, 3290, 'Arrendamientos de sustancias y productos químicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (32903, 3290, 'Otros arrendamientos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33101, 3310, 'Asesorías asociadas a convenios, tratados o acuerdos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33102, 3310, 'Asesorías por controversias en el marco de los tratados internacionales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33103, 3310, 'Consultorías para programas o proyectos financiados por organismos internacionales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33104, 3310, 'Otras asesorías para la operación de programas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33105, 3310, 'Servicios relacionados con procedimientos jurisdiccionales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33201, 3320, 'Servicios de diseño, arquitectura, ingeniería y actividades relacionadas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33301, 3330, 'Servicios de desarrollo de aplicaciones informáticas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33302, 3330, 'Servicios estadísticos y geográficos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33303, 3330, 'Servicios relacionados con certificación de procesos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33304, 3330, 'Servicio de mantenimiento de aplicaciones informáticas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33401, 3340, 'Servicios para Capacitacion a servidores públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33501, 3350, 'Estudios e investigaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33601, 3360, 'Servicios relacionados con traducciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33602, 3360, 'Otros servicios comerciales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33603, 3360, 'Impresiones de documentos oficiales para la prestación de servicios públicos, identificación, formatos administrativos y fiscales, formas valoradas, certificados y títulos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33604, 3360, 'Impresión y elaboración de material informativo derivado de la operación y administracion de las dependencias y entidades');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33605, 3360, 'Información en medios masivos derivada de la operación y administracion de las dependencias y entidades');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33606, 3360, 'Servicio de digitalización');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33701, 3370, 'Gastos de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33702, 3370, 'Gastos en actividades de seguridad y logística del Estado Mayor Presidencial');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33801, 3380, 'Servicios de vigilancia');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33901, 3390, 'Subcontratación de servicios con terceros');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33902, 3390, 'Proyectos para prestación de servicios');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (33903, 3390, 'Servicios integrales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (34101, 3410, 'Servicios bancarios y financieros');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (34301, 3430, 'Gastos inherentes a la recaudación');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (34401, 3440, 'Seguros de responsabilidad patrimonial del Estado');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (34501, 3450, 'Seguro de bienes patrimoniales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (34601, 3460, 'Almacenaje, embalaje y envase');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (34701, 3470, 'Fletes y maniobras');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35101, 3510, 'Mantenimiento y conservación de inmuebles para la prestación de servicios administrativos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35102, 3510, 'Mantenimiento y conservación de inmuebles para la prestación de servicios públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35201, 3520, 'Mantenimiento y conservación de mobiliario y equipo de administracion');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35301, 3530, 'Mantenimiento y conservación de bienes informáticos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35401, 3540, 'Instalación, reparación y mantenimiento de equipo e instrumental médico y de laboratorio');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35501, 3550, 'Mantenimiento y conservación de vehículos terrestres, aéreos, marítimos, lacustres y fluviales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35601, 3560, 'Reparación y mantenimiento de equipo de defensa y seguridad');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35701, 3570, 'Mantenimiento y conservación de maquinaria y equipo');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35702, 3570, 'Mantenimiento y conservación de plantas e instalaciones productivas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35801, 3580, 'Servicios de lavandería, limpieza, higiene');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (35901, 3590, 'Servicios de jardinería y fumigación');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (36101, 3610, 'Difusión de mensajes sobre programas y actividades gubernamentales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (36201, 3620, 'Difusión de mensajes comerciales para promover la venta de productos o servicios');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (36300, 3630, 'Servicios de creatividad, preproducción y producción de publicidad, excepto Internet (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (36400, 3640, 'Servicios de revelado de fotografías (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (36500, 3650, 'Servicios de la industria fílmica, del sonido y del video (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (36600, 3660, 'Servicio de creación y difusión de contenido exclusivamente a través de Internet (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (36901, 3690, 'Servicios relacionados con monitoreo de información en medios masivos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37101, 3710, 'Pasajes aéreos nacionales para labores en campo y de supervisión');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37102, 3710, 'Pasajes aéreos nacionales asociados a los programas de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37103, 3710, 'Pasajes aéreos nacionales asociados a desastres naturales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37104, 3710, 'Pasajes aéreos nacionales para servidores públicos de mando en el desempeño de comisiones y funciones oficiales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37105, 3710, 'Pasajes aéreos internacionales asociados a los programas de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37106, 3710, 'Pasajes aéreos internacionales para servidores públicos en el desempeño de comisiones y funciones oficiales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37201, 3720, 'Pasajes terrestres nacionales para labores en campo y de supervisión');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37202, 3720, 'Pasajes terrestres nacionales asociados a los programas de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37203, 3720, 'Pasajes terrestres nacionales asociados a desastres naturales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37204, 3720, 'Pasajes terrestres nacionales para servidores públicos de mando en el desempeño de comisiones y funciones oficiales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37205, 3720, 'Pasajes terrestres internacionales asociados a los programas de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37206, 3720, 'Pasajes terrestres internacionales para servidores públicos en el desempeño de comisiones y funciones oficiales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37207, 3720, 'Pasajes terrestres nacionales por medio electrónico');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (37701, 3770, 'Instalación del personal federal');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (38201, 3820, 'Gastos de orden social');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (38301, 3830, 'Congresos y convenciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (38401, 3840, 'Exposiciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (38501, 3850, 'Gastos para alimentación de servidores públicos de mando');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (39101, 3910, 'Funerales y pagas de defunción');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (39602, 3960, 'Otros gastos por responsabilidades');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (51101, 5110, 'Mobiliario');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (51201, 5120, 'Muebles, excepto de oficina y estantería');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (51301, 5130, 'Bienes artísticos y culturales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (51501, 5150, 'Bienes informáticos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (51901, 5190, 'Equipos de administracion');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (52101, 5210, 'Equipos y aparatos audiovisuales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (52201, 5220, 'Aparatos deportivos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (52301, 5230, 'Cámaras fotográficas y de video');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (52901, 5290, 'Otro mobiliario y equipo educacional y recreativo');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (53101, 5310, 'Equipo medico y de laboratorio');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (53201, 5320, 'Instrumental medico y de laboratorio');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54101, 5410, 'Vehículos y equipo terrestres, para la ejecución de programas de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54103, 5410, 'Vehículos y equipo terrestres, destinados a servicios públicos y la operación de programas públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54201, 5420, 'Carrocerías y remolques');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54303, 5430, 'Vehículos y equipo aéreos, destinados a servicios públicos y la operación de programas públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54401, 5440, 'Equipo ferroviario');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54501, 5450, 'Vehículos y equipo marítimo, para la ejecución de programas de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54502, 5450, 'Vehículos y equipo marítimo, destinados a servicios públicos y la operación de programas públicos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54503, 5450, 'Construcción de embarcaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (54901, 5490, 'Otros equipos de transporte');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (55101, 5510, 'Maquinaria y equipo de defensa y seguridad Pública');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (55102, 5510, 'Equipo de seguridad pública y nacional');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56101, 5610, 'Maquinaria y equipo agropecuario');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56201, 5620, 'Maquinaria y equipo industrial');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56301, 5630, 'Maquinaria y equipo de construcción');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56401, 5640, 'Sistemas de aire acondicionado, calefacción y de refrigeración industrial y comercial');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56501, 5650, 'Equipo y aparatos de comunicaciones y telecomunicaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56601, 5660, 'Maquinaria y equipo eléctrico y electrónico');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56701, 5670, 'Herramientas y maquinas herramienta');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (56902, 5690, 'Otros bienes muebles');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (57101, 5710, 'Animales de reproducción');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (57201, 5720, 'Porcinos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (57401, 5740, 'Ovinos y caprinos');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (57501, 5750, 'Peces y acuicultura');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (57601, 5760, 'Animales de trabajo');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (57701, 5770, 'Animales de custodia y vigilancia');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (57801, 5780, 'Árboles y plantas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (58904, 5890, 'Otros bienes inmuebles');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (59101, 5910, 'Software');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (61200, 6120, 'Edificación no habitacional (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (61300, 6130, 'Construcción de obras para el abastecimiento de agua, petróleo, gas, electricidad y telecomunicaciones (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (61500, 6150, 'Construcción de vías de comunicación (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (61600, 6160, 'Otras Construcciones de ingeniería civil u obra pesada (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (61700, 6170, 'Instalaciones y equipamiento en Construcciones (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (61900, 6190, 'Trabajos de acabados en edificaciones y otros trabajos especializados (NO EXISTE PARTIDA ESPECÍFICA)');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62101, 6210, 'Obras de construcción para edificios habitacionales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62102, 6210, 'Mantenimiento y rehabilitación de edificaciones habitacionales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62201, 6220, 'Obras de construcción para edificios no habitacionales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62202, 6220, 'Mantenimiento y rehabilitación de edificaciones no habitacionales');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62301, 6230, 'Construcción de obras para el abastecimiento de agua, petróleo, gas, electricidad y telecomunicaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62302, 6230, 'Mantenimiento y rehabilitación de obras para el abastecimiento de agua, petróleo, gas, electricidad y telecomunicaciones');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62401, 6240, 'Obras de preedificación en terrenos de construcción');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62402, 6240, 'Construcción de obras de urbanización');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62403, 6240, 'Mantenimiento y rehabilitación de obras de urbanización');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62501, 6250, 'Construcción de vías de comunicación');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62502, 6250, 'Mantenimiento y rehabilitación de las vías de comunicación');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62601, 6260, 'Otras construcciones de ingeniería civil u obra pesada');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62602, 6260, 'Mantenimiento y rehabilitación de otras obras de ingeniería civil u obras pesadas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62701, 6270, 'Instalaciones y obras de construcción especializada');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62901, 6290, 'Ensamble y edificación de construcciones prefabricadas');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62902, 6290, 'Obras de terminación y acabado de edificios');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62903, 6290, 'Servicios de supervisión de obras');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62904, 6290, 'Servicios para la liberación de derechos de vía');
insert into partida_especifica (id_partida_especifica, id_partida_generica, descripcion) values (62905, 6290, 'Otros servicios relacionados con obras Públicas');
